# Generated by Django 6.0 on 2025-12-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=100)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('prep_time_minutes', models.IntegerField()),
                ('ingredients', models.JSONField()),
                ('difficulty', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
